project_id = "cgtvvpzrzwyvsbavboxa"

[functions.generate-ai-question]
verify_jwt = true

[functions.create-payment]
verify_jwt = true

[functions.seed-test-users]
verify_jwt = true

[functions.import-emgurus]
verify_jwt = true

[functions.blog-record-view]
verify_jwt = false

[functions.blog-toggle-like]
verify_jwt = true

[functions.consultations-api]
verify_jwt = false

[functions.seed-sample-gurus]
verify_jwt = false

[functions.guru-applications]
verify_jwt = true
